### ISSUE TITLE
Support deploying multiple relay modules to 1 AWS account

### ISSUE THREAD

**Issue by irosenbery** [fullstorydev/terraform-aws-fullstory-cloud-relay#12]
Currently it is not possible to directly create multiple instances of the fullstory relay in the same AWS account (at least when specifying the relay_fqdn + route53_zone_name, I didn't try the other option). This is because the cloudfront origin request policy which is created has a static name, so any modules besides the first will fail to create the resource.

To overcome this I manually edited the terraform cached state file for the module to set the policy name to something unique, but this is overridden when the state is refreshed and won't work with multiple developers on the project.

I have a fork of the repo and am about to create a PR for this, but am creating the issue since it is requested in the PR format. (and probably makes sense for tracking)

There are a few ways to solve this, but I have a fairly simple one which I will explain as part of the PR.

**Comment by SamKirsch10** [comment]
Again thanks for your contribution! Closing.
